# Generated by Django 4.2.2 on 2023-06-29 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("immobile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_platform", models.DecimalField(decimal_places=2, max_digits=6)),
                ("name_platform", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "immobile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="immobile.immobile",
                    ),
                ),
            ],
        ),
    ]
